### PR TITLE
Implement 'Calculator' front-end for Decodables

### PR DESCRIPTION
**Pull request by igorbonadio**

### CODE REVIEW

**Comment by renatocf** [comment]
@igorbonadio,

Before we merge it, I'd suggest just one change: change the use of `double` by the alias `Probability`. This is a better approach because it has a better semantic meaning, and if we eventually decide to change the type (for `float` or a multiprecision library), it will be easy to change the entire system. Also, issue #50 will introduce assertions to guarantee all `Probability` return are within the range [0,1].

I believe to make things even better, we should also introduce an alias `Infinity`, defined as `std::numeric_limits<double>::infinity()`. It's not only less verbose but would have the same advantages of the alias `Probability`. But that's a change for another issue.

**Comment by renatocf** [comment]
Created: #53. As this is a simple task, we can assign it to Bruno or Ademar, or you yourself can change it quickly if you want so.

**Comment by igorbonadio** [comment]
I tried to change all probabilities values to `Probability` type. In fact `std::numeric_limits<double>::infinity()` is `std::numeric_limits<Probability>::infinity()` now.

**Comment by renatocf** [comment]
Perfect. We can merge it. Afterward take a look at my comments in #53. Maybe we should think in a more meaningful type system for values that will differentiate probabilities from logarithm of probabilities.

**Pull request merged**
